name: single_job
on:
  workflow_call:
    inputs:
      task-id:
        required: true
        type: string
      task-name:
        required: true
        type: string
jobs:
    batch_job:
      runs-on: ubuntu-latest
      steps:
        - name: show full task name
          run: echo "${{ inputs.task-name }}"
        - name: sync code
          uses: actions/checkout@v4
        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: install packages
          run: "pip install --upgrade pip\npython -m pip install --upgrade setuptools\
            \ \npython -m pip install -r requirements.txt\n"
        - env:
            DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
            DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
            DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          name: run task
          run: python run_task.py ${{ inputs.task-id }}